import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/nav";
import Footer from "@/components/footer";

const syne = Syne({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en ">
      <body className={cn("min-h-screen antialiased", syne.className)}>
        <NavBar />
        <div className="flex flex-col min-h-screen mx-auto">{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
